### ISSUE TITLE
[S03 T02] 장르, Sort 종류는 내부 모델(enum)으로 구현한다.

### ISSUE THREAD

**Issue by jeffoio** [boostcampwm-2021/iOS05-Escaper#3]
### Epic - Story - Task

Epic :   상세 분류 페이지
Story :  상세 분류 페이지 화면을 구성한다.
Task :  장르, Sort 종류는 내부 모델(enum)으로 구현한다.

**Comment by wansook0316** [comment]
1. 장르 enum
2. Asset 넣기
3. SortingOptions enum
