### ISSUE TITLE
[E03 T07] 데이터를 가져오지 못 할 경우 검색결과가 없는 뷰를 보여준다.

### ISSUE THREAD

**Issue by shinhee-rebecca** [boostcampwm-2021/iOS05-Escaper#9]
### Epic - Story - Task

Epic :  상세 분류 페이지
Story : 사용자가 원하는 방탈출 방의 조건을 선택하면 데이터를 sorting해서 보여준다.
Task : 데이터를 가져오지 못 할 경우 검색결과가 없는 뷰를 보여준다.

**Comment by wansook0316** [comment]
안함
